#!/usr/bin/env node
/**
 * Wraps the intermediate CSS files Style Dictionary generates (_primitive.css,
 * _semantic.css, _theme-dark.css, _brand-pilot.css) in their cascade layers,
 * and writes the final tokens.css — Theme Runtime Chunks 01, 03, and 05.
 *
 * Why a text-level wrap instead of a custom Style Dictionary format: the
 * built-in css/variables formatter already correctly handles outputReferences
 * (var() chains), description comments, and the composite shadow/typography
 * serialization proven in Token Foundation/Semantic Layer. Reimplementing
 * that from token objects to add @layer risks silently regressing formatting
 * that already works. Treating its output as a correct, opaque text block
 * and wrapping it is the lower-risk option.
 *
 * The five-layer order is declared once here — every later Theme Runtime
 * chunk (brand, component) extends this same declaration; nothing downstream
 * should re-declare @layer with a different order.
 *
 * tokens.theme deliberately has NO `[data-theme="light"]` block restating the
 * light values. tokens.semantic already sets every semantic custom property
 * unconditionally in :root — if data-theme is absent, or ="light", nothing in
 * the theme layer matches, so the semantic layer's value is simply what
 * applies. The theme layer only ever needs to state deltas from that default.
 * Restating light values here would be pure duplication with no behavioral
 * difference, since a later layer with no matching selector can't win.
 *
 * tokens.brand (Chunk 05) is positioned between tokens.semantic and
 * tokens.theme in BOTH the bare @layer declaration below and the physical
 * order of the populated blocks — though only the declaration line actually
 * controls precedence (a layer's position is fixed by wherever its name is
 * FIRST mentioned; populated blocks after that just add content to an
 * already-positioned layer). It overrides primitive custom properties
 * (--ds-color-brand-9, not --ds-color-action-primary) — see
 * decisions/decision-brand-override-targets-primitives.md for why that's
 * what lets a brand override survive dark mode being active too, despite
 * tokens.brand being declared before tokens.theme.
 */
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";

const buildDir = new URL("../build/css/", import.meta.url);

function readLayerBody(filename) {
  const raw = readFileSync(new URL(filename, buildDir), "utf8");
  // Strip the auto-generated header comment and the outer :root { ... } —
  // we re-wrap the same body in our own layer structure below.
  const match = raw.match(/:root\s*{([\s\S]*)}\s*$/);
  if (!match) {
    throw new Error(`assemble-layers: couldn't find a :root block in ${filename}`);
  }
  return match[1].trimEnd();
}

const primitiveBody = readLayerBody("_primitive.css");
const semanticBody = readLayerBody("_semantic.css");
const themeDarkBody = readLayerBody("_theme-dark.css");
const brandPilotBody = readLayerBody("_brand-pilot.css");

const output = `/**
 * Do not edit directly, this file was auto-generated by
 * scripts/assemble-layers.mjs from _primitive.css + _semantic.css +
 * _theme-dark.css + _brand-pilot.css.
 */

@layer tokens.primitive, tokens.semantic, tokens.brand, tokens.theme, tokens.component;

@layer tokens.primitive {
  :root {${primitiveBody}
  }
}

@layer tokens.semantic {
  :root {${semanticBody}
  }
}

@layer tokens.brand {
  [data-brand="pilot"] {${brandPilotBody}
  }
}

@layer tokens.theme {
  [data-theme="dark"] {${themeDarkBody}
  }
}
`;

writeFileSync(new URL("tokens.css", buildDir), output);
unlinkSync(new URL("_primitive.css", buildDir));
unlinkSync(new URL("_semantic.css", buildDir));
unlinkSync(new URL("_theme-dark.css", buildDir));
unlinkSync(new URL("_brand-pilot.css", buildDir));

console.log(
  "Wrote build/css/tokens.css with @layer tokens.primitive + tokens.semantic + tokens.brand + tokens.theme",
);
