#!/usr/bin/env node
/**
 * Generates every icon component from Lucide's raw SVG source. Modeled
 * directly on packages/design-system/scripts/generate-atomic-css.mjs's own
 * shape — a plain Node script, run as part of `pnpm build`, not a bundler
 * plugin. See decisions/decision-icon-generation-pipeline.md and
 * decisions/decision-icon-generated-files-gitignored.md.
 *
 * Two-layer generation, deliberately not one custom SVGR template:
 * 1. SVGR's own default template (ref-forwarding, props-spreading, real
 *    TypeScript types) converts each raw SVG into a "raw" component —
 *    SVGR doing exactly what it's built and well-tested for, zero custom
 *    AST manipulation.
 * 2. A thin, hand-templated wrapper (plain string interpolation, not SVGR)
 *    imports the raw component and applies this project's own aria-hidden/
 *    size/color logic on top — see resolveIconProps.ts.
 *
 * Confirmed directly (2026-08-27): Lucide's raw SVGs already declare
 * stroke="currentColor" once on the root <svg>, inherited by every child
 * automatically — no fill/stroke AST rewrite step is needed here, unlike
 * Blade's own pipeline (which rewrites literal hex fills from Figma-sourced
 * SVGs). Lucide's own `class="lucide lucide-x"` attribute IS stripped
 * explicitly via svgo's removeAttrs — SVGO's preset-default does not strip
 * `class` on its own (it doesn't know it's meaningless in this context).
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync } from "node:fs";
import { transform } from "@svgr/core";
import { ICON_LIST } from "./icon-list.mjs";

const iconsDir = new URL("../node_modules/lucide-static/icons/", import.meta.url);
const generatedDir = new URL("../src/generated/", import.meta.url);
const rawDir = new URL("../src/generated/_raw/", import.meta.url);
const buildDir = new URL("../build/", import.meta.url);

rmSync(generatedDir, { recursive: true, force: true });
mkdirSync(rawDir, { recursive: true });

const svgrConfig = {
  typescript: true,
  ref: true,
  expandProps: "end",
  jsxRuntime: "automatic",
  plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
  svgoConfig: {
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            // preset-default strips viewBox whenever it's numerically
            // redundant with width/height (exactly Lucide's case:
            // viewBox="0 0 24 24" + width="24" height="24") — caught by
            // inspecting real generated output, not assumed safe. Without
            // viewBox, resizing the icon via our own CSS width/height
            // classes would stretch/crop it instead of scaling the
            // internal path coordinates proportionally.
            removeViewBox: false,
          },
        },
      },
      // Strips Lucide's own `class="lucide lucide-x"` — not part of
      // svgo's preset-default (it doesn't know `class` is meaningless
      // once converted to a React component with its own className).
      { name: "removeAttrs", params: { attrs: "(class)" } },
    ],
  },
};

for (const { lucideName, componentName } of ICON_LIST) {
  const svgPath = new URL(`${lucideName}.svg`, iconsDir);
  const svgSource = readFileSync(svgPath, "utf8");
  const rawComponentName = `${componentName}Raw`;

  const rawCodeRaw = await transform(svgSource, svgrConfig, { componentName: rawComponentName });
  // SVGR's default output imports `Ref` as a value import; this project's
  // tsconfig has verbatimModuleSyntax: true, which requires it as a
  // type-only import. Caught by a real tsc run, not assumed — SVGR has no
  // config flag for this, so it's fixed here as a straightforward,
  // deterministic string substitution on SVGR's own known output shape.
  const rawCode = rawCodeRaw.replace(
    'import { Ref, forwardRef } from "react";',
    'import { forwardRef } from "react";\nimport type { Ref } from "react";',
  );
  writeFileSync(new URL(`${rawComponentName}.tsx`, rawDir), rawCode);

  const wrapperCode = `/**
 * Do not edit directly — generated by scripts/generate-icons.mjs from
 * lucide-static's "${lucideName}" source. See scripts/icon-list.mjs for the
 * real, hand-reviewed list this is derived from.
 */
import { forwardRef } from "react";
import type { SVGProps } from "react";
import { resolveIconClassName } from "../resolveIconProps";
import type { IconOwnProps } from "../resolveIconProps";
import ${rawComponentName} from "./_raw/${rawComponentName}";

export const ${componentName} = forwardRef<SVGSVGElement, IconOwnProps & Omit<SVGProps<SVGSVGElement>, "color">>(
  function ${componentName}({ size = "medium", color, className, ...rest }, ref) {
    return (
      <${rawComponentName}
        ref={ref}
        {...rest}
        aria-hidden="true"
        className={resolveIconClassName(size, color, className)}
      />
    );
  },
);
`;
  writeFileSync(new URL(`${componentName}.tsx`, generatedDir), wrapperCode);
}

const barrelCode = `/**
 * Do not edit directly — generated by scripts/generate-icons.mjs, same run
 * that produces every icon component above.
 */
${ICON_LIST.map(({ componentName }) => `export { ${componentName} } from "./${componentName}";`).join("\n")}
export type { IconOwnProps, IconSize, IconColor } from "../resolveIconProps";
`;
writeFileSync(new URL("index.tsx", generatedDir), barrelCode);

mkdirSync(buildDir, { recursive: true });
copyFileSync(new URL("../src/icon.css", import.meta.url), new URL("icon.css", buildDir));

console.log(`Generated ${ICON_LIST.length} icons + barrel + icon.css.`);
